# Listado de usuarios, claves y perfiles.
usuarios = {
    "ADMIN": {'password': 'admin', 'perfil': 'admin', 'failed_login_count': 0},
    "TEST": {'password': 'test', 'perfil': 'mecanico', 'failed_login_count': 0},
    "BLOQUEADO": {'password': 'test', 'perfil': 'mecanico', 'failed_login_count': 3},
    "NUEVO": {'password': '83?ps=FL', 'perfil': 'mecanico', 'failed_login_count': 0},
    "MARIANO": {'password': '4y&yK3O>', 'perfil': 'admin', 'failed_login_count': 0},
    "CARLOS": {'password': 'AAbb11##', 'perfil': 'mecanico', 'failed_login_count': 0},
    "LUIS": {'password': 'QQww33++', 'perfil': 'admin', 'failed_login_count': 0},
    "JOSE": {'password': 'KKpp88??', 'perfil': 'mecanico', 'failed_login_count': 0},
    "TEST11": {'password': 'test', 'perfil': 'mecanico', 'failed_login_count': 3},
    "TEST12": {'password': 'test', 'perfil': 'mecanico', 'failed_login_count': 3},
    "TEST13": {'password': 'test', 'perfil': 'mecanico', 'failed_login_count': 3},
    "TEST14": {'password': 'test', 'perfil': 'mecanico', 'failed_login_count': 3},
    "TEST15": {'password': 'test', 'perfil': 'mecanico', 'failed_login_count': 3},
    "PILAR": {'password': 'Peperoni1234.', 'perfil': 'admin', 'failed_login_count': 0},
    "LAUTARO": {'password': ';t2KFp9<', 'perfil': 'mecanico', 'failed_login_count': 0},
    "FERNANDO": {'password': 'h8Gg1;{X', 'perfil': 'mecanico', 'failed_login_count': 0},
    "GABRIEL": {'password': '2uAqD;{5', 'perfil': 'mecanico', 'failed_login_count': 0},
    "MARCELO": {'password': ';z(L8m9Q', 'perfil': 'mecanico', 'failed_login_count': 0},
}
